language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only: master
install: npm install

notifications:
  slack: feshinc:jd5vYVkVDQeozpFUc1yBgUpm

jobs:
  include:
  - stage: test
    script: npm test

  - stage: build
    script: npm run prepare

  - stage: npm release  
    deploy:
      provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      on:
        tags: true
        branch: master